### ISSUE TITLE
Lambda reports success, no data in ES

### ISSUE THREAD

**Issue by danieldevcic** [neillturner/terraform-aws-alb-logs-to-elasticsearch#2]
![image](https://user-images.githubusercontent.com/49559601/110998452-1fa62700-837f-11eb-9c6b-70fc3710bb49.png)
 
I added additional logging, script is missing some error handling, any 4xx response should fail the script, instead it reports a success message as it sent the data to ES.

**Comment by baptiste-s** [comment]
have you check the correct index ? it should be named alblogs-(...)

**Comment by xsnrg** [comment]
There is a problem where the lambda would only work in the default region. The logging still says it sent the records, which it did, but they get rejected by ES. The PR makes the region a required variable to be defined in the module, and then passes it to the lambda.

**Comment by xsnrg** [comment]
@baptiste-s A PR was merged to master that I believe will fix your issue. Please try version 0.2.3
