### ISSUE TITLE
Make possible to use your own zip file for lambda filename

### ISSUE THREAD

**Issue by tcarrondo** [neillturner/terraform-aws-alb-logs-to-elasticsearch#9]
To keep the module retro compatible it could have a default variable with value "${path.module}/alb-logs-to-elasticsearch.zip"

**Comment by tcarrondo** [comment]
My suggestion:
https://github.com/neillturner/terraform-aws-alb-logs-to-elasticsearch/pull/10

**Comment by neillturner** [comment]
released as version 0.3.0
